name: Update README Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update stats badges to custom Vercel endpoint
        run: |          
          sed -i 's|https://github-readme-stats\.vercel\.app|https://github-readme-stats-2cxiez21p-jose-luis-guerreros-projects.vercel.app|g' README.md
                    
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add README.md
          git commit -m "chore: update stats badges to custom Vercel endpoint" || echo "No changes to commit"
          git push